### ISSUE TITLE
Release monochrom

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monochrom#1]
## minimal for release

 * [x] Create a GH repo using ODK
    * we would do a manual step of copying the ttl to this repo
 * [ ] Ensure all labels are included
 * [ ] Fix OWL errors (see below)

OWL error:

![image](https://user-images.githubusercontent.com/50745/60544850-84663e80-9cce-11e9-8622-c305412608b4.png)

# things to include in future

not urgent, just good to have them tracked

 * [ ] syntenic regions
 * [ ] chromosome positions

**Comment by TomConlin** [comment]
@TomConlin note to self figure out populating this from dipper

**Comment by matentzn** [comment]
@cmungall, is this correct that before makeing a release, we download the turtle dump from dipper using a make goal like:

```
edit:
	wget https://data.monarchinitiative.org/ttl/monochrom.ttl -O chr-edit.ttl
```

Seems that your current chr-edit.ttl differs massively (huge diff, but also things like ontology header which is not present in the dipper dump). What other processing does chr-edit.ttl need after the above download?

**Comment by cmungall** [comment]
Yes, something like that (apologies, I should have included this in the Makefile). It looks like it was passed through the owlapi in the first place (the Error1s).

Are you sure the diff is so large? Is this ascii, rdf-level, or owl-level?

Note also this would be the point of comparison (or even the version before this).
https://archive.monarchinitiative.org/201907/ttl/monochrom.ttl

I would not worry too much about replicating the original edit file. There was no manual massaging. Let's just start with the existing one and move forward. There are some oddities to deal with. Not sure if it makes sense to fix these as dipper or as post-processing.

The main oddities are in the rdf/owl conversion.

**Comment by matentzn** [comment]
Ah I only now saw this with the OWL errors - this needs to be fixed at dipper level.. I made a separate ticket: #2

**Comment by matentzn** [comment]
I updated the ODK to the latest version and included the monochrom dipper dump as a component in the pipeline - now its all handled correctly.. 

I will include monochrom now as part of Monarch OLS, but I have not dealt with the Error classes yet, nor have I looked at the labels "ensure all labels are included" -> How do I do that?

**Comment by cmungall** [comment]
dupe w #10
