### ISSUE TITLE
Weird Error classes in Dipper turtle output of monochrom

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monochrom#2]
![image](https://user-images.githubusercontent.com/7070631/82196826-dde55500-9902-11ea-9f52-b9533b4b9984.png)

FYI @kshefchek @TomConlin

**Comment by matentzn** [comment]
The corresponding turtle is this:

```
OBO:CHR_9606chr1 a owl:Class ;
    rdfs:label "chr1 (Human)" ;
    rdfs:subClassOf OBO:SO_0000340,
        <http://monarchinitiative.org/.well-known/genid/RO0002350_NCBITaxon9606genome>,
        <http://monarchinitiative.org/.well-known/genid/RO0002524CHR9606chr1p>,
        <http://monarchinitiative.org/.well-known/genid/RO0002524CHR9606chr1q> .
```

@cmungall can you fix this? It seems that this is not really valid OWL..

**Comment by matentzn** [comment]
(I mean, can you tell me what the intended syntax is here for that example class, I can piece the rest together)

**Comment by TomConlin** [comment]
wild guess  but suspect the subclass relation between chr1 and chr1[pq] is backwards

**Comment by matentzn** [comment]
@TomConlin will you ping me when you had a chance to rerun the dipper ingest without skolemisation? Thanks a lot :)

**Comment by TomConlin** [comment]
Jenkins was updated to not Skolemized blank nodes for Monochrom any more.
The the weekly dipper pipeline ran the output is here:
 https://data.monarchinitiative.org/dev/monochrom.ttl

**Comment by matentzn** [comment]
Hey @TomConlin , thanks, just checked this. There is still this issue:

```
_:RO0002350_NCBITaxon10090genome a owl:Restriction ;
    owl:onProperty OBO:RO_0002350 ;
    owl:someValuesFrom "_:NCBITaxon:10090genome" .
```

While this seems like legal RDF, in OWL, this is not possible; this would need to be an anymous expression like:

```
OBO:CHR_10090chr1 a owl:Class ;
    rdfs:label "chr1 (Mouse)" ;
    rdfs:subClassOf _:RO0002350_NCBITaxon10090genome, # <--- Not possible
        [ a owl:Restriction ; # <--- Correct
            owl:onProperty OBO:RO_0002524 ;
            owl:someValuesFrom OBO:CHR_10090chr1q ],
        OBO:SO_0000340 .
```

Thanks :)

**Comment by cmungall** [comment]
fixed by new pipeline
